"""Evaluate prediction arrays against OpenFOAM truth on the sampled cells."""
import argparse
import json
import re
from pathlib import Path

import numpy as np
import pyvista as pv


FIELD_MAP = {
    "U": "U",
    "p": "p",
    "k": "k",
    "nut": "nut",
    "omega_turb": "omega",
}
NON_NEGATIVE_FIELDS = {"k", "nut", "omega_turb"}


def read_omega(case_dir: Path) -> float:
    mrf = case_dir / "constant" / "MRFProperties"
    if mrf.exists():
        match = re.search(r"omega\s+constant\s+([0-9.eE+-]+)", mrf.read_text())
        if match:
            return float(match.group(1))
    match = re.search(r"([0-9.]+)\s*RAD", case_dir.name, re.IGNORECASE)
    if match:
        return float(match.group(1))
    raise ValueError(f"cannot determine omega for {case_dir}")


def discover_cases(input_dir: Path) -> dict[float, Path]:
    cases = {}
    for case_dir in sorted(input_dir.iterdir()):
        if case_dir.is_dir() and (case_dir / "case.foam").exists():
            cases[read_omega(case_dir)] = case_dir
    if not cases:
        raise FileNotFoundError(f"no OpenFOAM case folders found in {input_dir}")
    return cases


def load_truth(case_dir: Path) -> dict[str, np.ndarray]:
    reader = pv.POpenFOAMReader(str(case_dir / "case.foam"))
    reader.set_active_time_value(reader.time_values[-1])
    reader.enable_all_cell_arrays()
    reader.cell_to_point_creation = False
    mesh = reader.read()["internalMesh"]
    return {
        pred_name: np.asarray(mesh.cell_data[foam_name], dtype=np.float32)
        for pred_name, foam_name in FIELD_MAP.items()
    }


def scalar_metrics(pred: np.ndarray, truth: np.ndarray, non_negative: bool) -> dict[str, float]:
    err = pred - truth
    mae = float(np.mean(np.abs(err)))
    mean_abs = float(np.mean(np.abs(truth)))
    metrics = {
        "rmse": float(np.sqrt(np.mean(err**2))),
        "mae": mae,
        "rel_mae_meanabs": mae / (mean_abs + 1e-12),
        "truth_min": float(np.min(truth)),
        "truth_max": float(np.max(truth)),
        "pred_min": float(np.min(pred)),
        "pred_max": float(np.max(pred)),
    }
    if non_negative:
        metrics["pred_negative_fraction"] = float(np.mean(pred < 0))
    return metrics


def vector_metrics(pred: np.ndarray, truth: np.ndarray) -> dict[str, float]:
    err = pred - truth
    pred_mag = np.linalg.norm(pred, axis=1)
    truth_mag = np.linalg.norm(truth, axis=1)
    return {
        "component_rmse": float(np.sqrt(np.mean(err**2))),
        "component_mae": float(np.mean(np.abs(err))),
        "magnitude_rmse": float(np.sqrt(np.mean((pred_mag - truth_mag) ** 2))),
        "truth_magnitude_mean": float(np.mean(truth_mag)),
        "pred_magnitude_mean": float(np.mean(pred_mag)),
        "truth_magnitude_max": float(np.max(truth_mag)),
        "pred_magnitude_max": float(np.max(pred_mag)),
    }


def prediction_omegas(predictions: np.lib.npyio.NpzFile) -> list[float]:
    return sorted({float(name.split("/")[0]) for name in predictions.files})


def load_frame(predictions: np.lib.npyio.NpzFile, omega: float) -> dict[str, np.ndarray]:
    prefix = f"{omega:.1f}/"
    return {
        name.split("/")[1]: predictions[name]
        for name in predictions.files
        if name.startswith(prefix)
    }


def evaluate_case(
    case_dir: Path,
    frame: dict[str, np.ndarray],
    sub_idx: np.ndarray | None,
) -> dict[str, dict[str, float]]:
    truth = load_truth(case_dir)
    result = {}
    for field, pred in frame.items():
        if field not in truth:
            continue
        truth_field = truth[field]
        if sub_idx is not None:
            truth_field = truth_field[sub_idx]
        if len(pred) != len(truth_field):
            raise ValueError(
                f"{case_dir.name}/{field}: prediction length {len(pred)} "
                f"does not match truth length {len(truth_field)}"
            )
        if field == "U":
            result[field] = vector_metrics(pred, truth_field)
        else:
            result[field] = scalar_metrics(pred, truth_field, field in NON_NEGATIVE_FIELDS)
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path("input"), help="OpenFOAM input directory.")
    parser.add_argument(
        "--predictions",
        type=Path,
        default=Path("out_outputs/predictions.npz"),
        help="Prediction NPZ generated by train.py.",
    )
    parser.add_argument(
        "--sub-idx",
        type=Path,
        default=Path("out_outputs/sub_idx.npy"),
        help="Sampled cell index array. Use --no-sub-idx for full-cell predictions.",
    )
    parser.add_argument("--no-sub-idx", action="store_true", help="Compare predictions to full mesh cells.")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("out_outputs/evaluation_metrics.json"),
        help="Metrics JSON output path.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_dir = args.input
    if not input_dir.is_dir() and args.input == Path("input"):
        input_dir = Path("D:/Work/input")

    cases = discover_cases(input_dir)
    predictions = np.load(args.predictions)
    pred_omegas = prediction_omegas(predictions)
    common_omegas = [omega for omega in pred_omegas if omega in cases]
    if not common_omegas:
        raise ValueError(f"no prediction omegas match OpenFOAM cases: {sorted(cases)}")

    sub_idx = None
    if not args.no_sub_idx:
        sub_idx = np.load(args.sub_idx)

    report = {
        "input": str(input_dir.resolve()),
        "predictions": str(args.predictions.resolve()),
        "sub_idx": None if sub_idx is None else str(args.sub_idx.resolve()),
        "cases": {},
    }

    for omega in common_omegas:
        frame = load_frame(predictions, omega)
        metrics = evaluate_case(cases[omega], frame, sub_idx)
        report["cases"][f"{omega:.1f}"] = metrics

        u = metrics.get("U", {})
        print(
            f"omega={omega:.1f} "
            f"U_rmse={u.get('component_rmse', float('nan')):.4g} "
            f"|U|max truth/pred="
            f"{u.get('truth_magnitude_max', float('nan')):.4g}/"
            f"{u.get('pred_magnitude_max', float('nan')):.4g}"
        )
        for field in ("p", "k", "nut", "omega_turb"):
            if field not in metrics:
                continue
            m = metrics[field]
            extra = ""
            if "pred_negative_fraction" in m:
                extra = f" neg={m['pred_negative_fraction']:.2%}"
            print(
                f"  {field:<10} rmse={m['rmse']:.4g} "
                f"mae={m['mae']:.4g} rel_mae={m['rel_mae_meanabs']:.3g}{extra}"
            )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2))
    print(f"Wrote metrics: {args.output}")


if __name__ == "__main__":
    main()
